# Generated by Django 5.1.4 on 2024-12-17 13:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('join_date', models.DateField()),
                ('employee_no', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('emp_start_date', models.DateField()),
                ('emp_end_date', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee_photos/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.department')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.designation')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.location')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
