# Generated by Django 5.1.4 on 2024-12-20 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='myapp.employee'),
        ),
    ]
