# Generated by Django 5.1.4 on 2025-01-28 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_employee_skills_alter_skill_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='skills',
        ),
    ]
