# Generated by Django 5.1.4 on 2025-02-04 07:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_employee_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='a2_general_organization_details_header',
            fields=[
                ('general_organization_details_header_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('organization_description_document_avaliable', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=10, null=True)),
                ('organization_description_document_file', models.FileField(blank=True, null=True, upload_to='audit_files')),
                ('is_there_an_independant_quality_assurance_department', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=10, null=True)),
                ('is_production_planned_systamatically', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=10, null=True)),
                ('production_plan_details', models.CharField(blank=True, max_length=500, null=True)),
                ('production_planning_and_control_system', models.CharField(blank=True, choices=[('Work Procedure', 'Work Procedure'), ('Index Cards', 'Index Cards')], default='', max_length=100, null=True)),
                ('is_delivery_timed_planned_and_monitored', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=10, null=True)),
                ('is_inform_customer_of_delay', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=10, null=True)),
                ('is_work_instruction_for_production', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=10, null=True)),
                ('is_work_instruction_for_in_process_inspection', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=10, null=True)),
                ('is_work_instruction_for_final_inspection', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=10, null=True)),
                ('is_work_instruction_for_outgoing_goods_inspection', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=10, null=True)),
                ('is_inspection_work_result_documented', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=10, null=True)),
                ('one_time_delivery_compalince_last_or_current_year_percentage', models.CharField(blank=True, max_length=50, null=True)),
                ('implemented_procedure_for_ensuring_non_conforming_products', models.CharField(blank=True, max_length=50, null=True)),
                ('written_work_instructions_for_the_production_processes', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=5, null=True)),
                ('sendto_buyer_date', models.DateTimeField(blank=True, null=True)),
                ('filled_personname', models.CharField(blank=True, max_length=50, null=True)),
                ('filled_persondesignation', models.CharField(blank=True, max_length=50, null=True)),
                ('filled_personsignature', models.FileField(blank=True, null=True, upload_to='signature_docs')),
            ],
        ),
        migrations.AlterField(
            model_name='skill',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='myapp.employee'),
        ),
    ]
