# Generated by Django 5.1.4 on 2025-02-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_b10_material_inspection_testing_equipment_services_questionnaire_details_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b10_material_inspection_testing_equipment_services_questionnaire_details_header',
            name='liquid_penetrant_inspection',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
